# Generated by Django 5.1.5 on 2025-02-13 20:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_hero_cta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='potato',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
